### ISSUE TITLE
bug: finding..

### ISSUE THREAD

**Issue by cybermerlin** [maty21/mocha-sidebar#45]
Finding tests with Mocha on Node.js at "C:\nodejs\node.EXE"

**Comment by jmussman** [comment]
Issue #44 is the same issue as this one. Note the location where it is looking for tests. I'm having the same issue on a Mac, it looks for tests in the directory where Node is installed. Nobody else mentions any problems about the working directory, so I'm thinking this is a bug introduced in the most recent release 20 days ago?

**Comment by maty21** [comment]
I didn't understand what is the bug here does it's not informative or something else ?

**Comment by jmussman** [comment]
Hi! Maybe I don't understand something, but I did a default install of the extension and it looks for tests in the Node folder, on my computer at "/Users/jmussman/.nvm/versions/node/v8.9.3/bin/node." I tried it both in a workspace setting and in a single project setting, same results. There are no other mocha extensions installed. I see no setting to set the CWD for Mocha, although that would seem to be a bad way to start, because it should start in the project directory.

On that note though, what happens in a workspace? Is there any documentation on telling it which project to test in? If it can't work in a workspace environment, that's OK too, just need to know that.

Thanks,
Joel

**Comment by jmussman** [comment]
BTW, that was the error in issue #44 too, posted by someone else. That's why the alert at the top of the window in the screen shot, and you can see the path is in the Node directory at the bottom, not in the project directory.

**Comment by maty21** [comment]
You should ignore this message its not really looking for the test in that folder I should change this message :)

The issue in #44 is that I'm not printing the error on the status message that pops up so imo its not related to this one can you please explain what is your problem please 
If I understand mocha side bar did not found any tests although you have one it could be nice if you can share your mocha configuration and your test folder location it probably related to this tks

**Comment by jmussman** [comment]
Project directory, simple test, and mocha running at the command line:
![screen shot 2018-01-03 at 4 18 31 pm](https://user-images.githubusercontent.com/6170555/34540377-4e502826-f0a2-11e7-99d2-a412f55bc8db.png)

Trying to run all tests through the extension results in this:
![screen shot 2018-01-03 at 4 16 45 pm](https://user-images.githubusercontent.com/6170555/34540462-a593622e-f0a2-11e7-8407-23d9d77cbb49.png)

The only settings I have made are these:
![screen shot 2018-01-03 at 4 17 08 pm](https://user-images.githubusercontent.com/6170555/34540398-6800de46-f0a2-11e7-87bb-cb928e3f2f90.png)

If I'm doing something dumb that's OK. But it looks to me like all three of us have the same problem. I have Mocha installed globally and locally in the project; my PATH is set to prefer ./node_modules/.bin/mocha. That shouldn't matter as far as I can see, and from the output it looks like it is running Mocha, just in the wrong place.

**Comment by jmussman** [comment]
Oh, the mocha.opts file just has --recursive in it.

**Comment by maty21** [comment]
It's seems like that it's find test can you expend the mocha side bar  and check if see tests ?

**Comment by jmussman** [comment]
Maybe that's our problem. I just expected it to show automatically. This may sound dumb, but exactly how do I expand it?

**Comment by maty21** [comment]
Just click on the  triangle in the left side bare where mocha  is written

**Comment by jmussman** [comment]
Yes, that brings more joy. See, I am ignorant. Still, #1, I will bet it threw all three of us off because of the messages in the output. #2, An explanation of the colors in your documentation would be useful, because while Mocha itself runs all the tests green, I'm getting yellow here and the blue never changes in the sidebar. Should I be seeing green squares? Which is a different issue than #45 here so maybe we better move it.

**Comment by maty21** [comment]
Did you try to run your test via side bar or lens ?
Yellow/blue not run , green success, red failed

**Comment by jmussman** [comment]
I think it's my bad, the blue arrow doesn't run them in the sidebar. I see that you have to go in and right-click. I need to learn how to use the lens, that was my next step. Can you point me in the right direction?

**Comment by maty21** [comment]
Just click on them

**Comment by jmussman** [comment]
OK. I'm good. Thanks for all your help! I hope this thread will help someone else who blocks on seeing the messages about no tests, and mabye they shouldn't be there. Why is it looking for tests in the Node directory in the first place? Anyways, thanks again!

**Comment by maty21** [comment]
It's not just a bad message.
 you welcome enjoy 
btw if you like this extension you can 🌟 us tks :)
